# Generated by Django 3.0.8 on 2020-07-10 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrackerapp', '0003_project_schedule_task_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='first_hour',
            field=models.TimeField(default=datetime.time(8, 0), null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_hour',
            field=models.TimeField(default=datetime.time(17, 0), null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Task Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
