# Generated by Django 3.0.8 on 2020-07-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrackerapp', '0006_auto_20200712_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
    ]
