# Generated by Django 3.0.8 on 2020-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrackerapp', '0007_auto_20200712_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='roles',
            field=models.CharField(choices=[('manager', 'M'), ('superadmin', 'S'), ('employee', 'E')], max_length=20),
        ),
    ]
