# Generated by Django 3.0.8 on 2020-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrackerapp', '0008_auto_20200715_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
