# Generated by Django 3.0.8 on 2020-07-21 06:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrackerapp', '0010_auto_20200719_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimationTime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='module',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Mobile', 'M'), ('Backend', 'B'), ('Frontend', 'F')], max_length=10), max_length=110, size=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
