# Generated by Django 3.0.8 on 2020-07-26 07:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrackerapp', '0011_auto_20200721_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='roles',
            field=models.CharField(choices=[('manager', 'M'), ('employee', 'E'), ('superadmin', 'S')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='module',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Mobile', 'M'), ('Frontend', 'F'), ('Backend', 'B')], max_length=10), max_length=110, size=10),
        ),
    ]
