# Generated by Django 3.0.8 on 2020-07-26 13:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTrackerapp', '0012_auto_20200726_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='roles',
            field=models.CharField(choices=[('employee', 'E'), ('superadmin', 'S'), ('manager', 'M')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='module',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Mobile', 'M'), ('Backend', 'B'), ('Frontend', 'F')], max_length=10), max_length=110, size=10),
        ),
    ]
